import { useState } from 'react'
import {
  FileText,
  Download,
  Copy,
  Check,
  Sparkles,
  AlertCircle,
  Eye,
} from 'lucide-react'
import Card from '../components/Card'
import Button from '../components/Button'

const caseTypes = [
  { value: '', label: 'Select case type' },
  { value: 'maintenance', label: 'Maintenance Petition (Section 125 CrPC)' },
  { value: 'domestic-violence', label: 'Domestic Violence Complaint (PWDVA 2005)' },
  { value: 'divorce', label: 'Divorce Petition' },
  { value: 'harassment', label: 'Workplace Harassment (POSH Act 2013)' },
  { value: 'custody', label: 'Child Custody Petition' },
  { value: 'property', label: 'Property Partition Suit' },
  { value: 'dowry', label: 'Dowry Harassment Complaint' },
  { value: 'other', label: 'Other' },
]

const caseTypeLabels = Object.fromEntries(
  caseTypes.filter((t) => t.value).map((t) => [t.value, t.label]),
)

const emptyForm = {
  name: '',
  district: '',
  caseType: '',
  description: '',
}

function generatePetition({ name, district, caseType, description }) {
  const date = new Date().toLocaleDateString('en-IN', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  })

  const caseTitle = caseTypeLabels[caseType] || 'Legal Petition'

  return `IN THE COURT OF DISTRICT JUDGE
AT ${district.toUpperCase()}

${caseTitle.toUpperCase()}

Petitioner: ${name}
District: ${district}

MOST RESPECTFULLY SHOWETH:

1. That the Petitioner, ${name}, is a resident of ${district} district and submits this petition before this Hon'ble Court.

2. That the facts of the case are as follows:

   ${description}

3. That the Petitioner has exhausted all reasonable efforts to resolve the matter amicably and is compelled to seek relief from this Hon'ble Court.

4. That the Petitioner is entitled to relief under the applicable provisions of Indian law pertaining to ${caseTitle}.

PRAYER:

It is therefore most humbly prayed that this Hon'ble Court may be pleased to:

(a) Grant the relief sought by the Petitioner in accordance with law;
(b) Pass such other and further order(s) as this Hon'ble Court deems fit in the interest of justice.

Place: ${district}
Date: ${date}

                                    Petitioner
                                    ${name}

---
Generated by HAQMarg — For informational purposes only.
Please review with a registered advocate before filing in court.
`
}

export default function PetitionGenerator() {
  const [form, setForm] = useState(emptyForm)
  const [preview, setPreview] = useState('')
  const [hasGenerated, setHasGenerated] = useState(false)
  const [copied, setCopied] = useState(false)
  const [errors, setErrors] = useState({})

  const updateField = (field, value) => {
    setForm((prev) => ({ ...prev, [field]: value }))
    if (errors[field]) {
      setErrors((prev) => ({ ...prev, [field]: '' }))
    }
  }

  const validate = () => {
    const next = {}
    if (!form.name.trim()) next.name = 'Name is required'
    if (!form.district.trim()) next.district = 'District is required'
    if (!form.caseType) next.caseType = 'Please select a case type'
    if (!form.description.trim()) next.description = 'Description is required'
    else if (form.description.trim().length < 20)
      next.description = 'Please provide at least 20 characters'
    setErrors(next)
    return Object.keys(next).length === 0
  }

  const handleGenerate = (e) => {
    e.preventDefault()
    if (!validate()) return

    setPreview(generatePetition(form))
    setHasGenerated(true)
  }

  const handleReset = () => {
    setForm(emptyForm)
    setPreview('')
    setHasGenerated(false)
    setErrors({})
  }

  const handleCopy = async () => {
    if (!preview) return
    await navigator.clipboard.writeText(preview)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleDownload = () => {
    if (!preview) return
    const blob = new Blob([preview], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `haqmarg-petition-${form.caseType || 'draft'}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-12">
      <header className="text-center mb-8 sm:mb-10 animate-slide-up">
        <p className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-pink-50 text-pink-700 text-xs font-medium mb-4">
          <Sparkles className="w-3.5 h-3.5" aria-hidden="true" />
          Free petition drafts — no backend required
        </p>
        <h1 className="text-3xl sm:text-4xl font-bold text-gray-900">
          Petition Generator
        </h1>
        <p className="mt-2 text-gray-500 text-sm sm:text-base max-w-xl mx-auto">
          Fill in your details and preview a legal petition draft instantly
        </p>
      </header>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 lg:gap-8 items-start">
        {/* Form */}
        <Card>
          <div className="flex items-center gap-2 mb-6">
            <FileText className="w-5 h-5 text-primary-600" aria-hidden="true" />
            <h2 className="text-lg font-semibold text-gray-900">Petition Details</h2>
          </div>

          <form onSubmit={handleGenerate} noValidate className="space-y-5">
            <div>
              <label htmlFor="name" className="block text-sm font-medium text-gray-700 mb-1.5">
                Name <span className="text-red-500" aria-hidden="true">*</span>
              </label>
              <input
                id="name"
                type="text"
                value={form.name}
                onChange={(e) => updateField('name', e.target.value)}
                placeholder="Your full name"
                autoComplete="name"
                aria-required="true"
                aria-invalid={!!errors.name}
                aria-describedby={errors.name ? 'name-error' : undefined}
                className={`w-full px-4 py-2.5 rounded-xl border bg-white text-sm focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent ${
                  errors.name ? 'border-red-300' : 'border-pink-200'
                }`}
              />
              {errors.name && (
                <p id="name-error" className="mt-1 text-xs text-red-600" role="alert">
                  {errors.name}
                </p>
              )}
            </div>

            <div>
              <label htmlFor="district" className="block text-sm font-medium text-gray-700 mb-1.5">
                District <span className="text-red-500" aria-hidden="true">*</span>
              </label>
              <input
                id="district"
                type="text"
                value={form.district}
                onChange={(e) => updateField('district', e.target.value)}
                placeholder="e.g. Lucknow, Patna, Indore"
                aria-required="true"
                aria-invalid={!!errors.district}
                aria-describedby={errors.district ? 'district-error' : undefined}
                className={`w-full px-4 py-2.5 rounded-xl border bg-white text-sm focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent ${
                  errors.district ? 'border-red-300' : 'border-pink-200'
                }`}
              />
              {errors.district && (
                <p id="district-error" className="mt-1 text-xs text-red-600" role="alert">
                  {errors.district}
                </p>
              )}
            </div>

            <div>
              <label htmlFor="caseType" className="block text-sm font-medium text-gray-700 mb-1.5">
                Case Type <span className="text-red-500" aria-hidden="true">*</span>
              </label>
              <select
                id="caseType"
                value={form.caseType}
                onChange={(e) => updateField('caseType', e.target.value)}
                aria-required="true"
                aria-invalid={!!errors.caseType}
                aria-describedby={errors.caseType ? 'caseType-error' : undefined}
                className={`w-full px-4 py-2.5 rounded-xl border bg-white text-sm focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent ${
                  errors.caseType ? 'border-red-300' : 'border-pink-200'
                }`}
              >
                {caseTypes.map(({ value, label }) => (
                  <option key={value || 'empty'} value={value}>
                    {label}
                  </option>
                ))}
              </select>
              {errors.caseType && (
                <p id="caseType-error" className="mt-1 text-xs text-red-600" role="alert">
                  {errors.caseType}
                </p>
              )}
            </div>

            <div>
              <label htmlFor="description" className="block text-sm font-medium text-gray-700 mb-1.5">
                Description <span className="text-red-500" aria-hidden="true">*</span>
              </label>
              <textarea
                id="description"
                rows={6}
                value={form.description}
                onChange={(e) => updateField('description', e.target.value)}
                placeholder="Describe your case — include key facts, dates, incidents, and the relief you are seeking…"
                aria-required="true"
                aria-invalid={!!errors.description}
                aria-describedby={errors.description ? 'description-error' : 'description-hint'}
                className={`w-full px-4 py-2.5 rounded-xl border bg-white text-sm focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent resize-none ${
                  errors.description ? 'border-red-300' : 'border-pink-200'
                }`}
              />
              <p id="description-hint" className="mt-1 text-xs text-gray-400">
                Minimum 20 characters
              </p>
              {errors.description && (
                <p id="description-error" className="mt-1 text-xs text-red-600" role="alert">
                  {errors.description}
                </p>
              )}
            </div>

            <div className="flex flex-col sm:flex-row gap-3 pt-2">
              <Button type="submit" className="flex-1 justify-center">
                <Sparkles className="w-4 h-4" aria-hidden="true" />
                Generate Petition
              </Button>
              {hasGenerated && (
                <Button
                  type="button"
                  variant="ghost"
                  onClick={handleReset}
                  className="flex-1 justify-center"
                >
                  Reset Form
                </Button>
              )}
            </div>
          </form>
        </Card>

        {/* Preview */}
        <div className="lg:sticky lg:top-20">
          <Card padding="p-0" className="overflow-hidden flex flex-col min-h-[420px]">
            <div className="flex items-center justify-between px-5 py-4 border-b border-pink-100 bg-white/70">
              <div className="flex items-center gap-2">
                <Eye className="w-5 h-5 text-primary-600" aria-hidden="true" />
                <h2 className="text-lg font-semibold text-gray-900">Preview</h2>
              </div>
              {hasGenerated && (
                <span className="text-xs font-medium text-green-600 bg-green-50 px-2.5 py-1 rounded-full border border-green-200">
                  Draft ready
                </span>
              )}
            </div>

            <div
              className="flex-1 overflow-y-auto bg-gray-50/60"
              role="region"
              aria-label="Petition preview"
              aria-live="polite"
            >
              {hasGenerated ? (
                <pre className="p-5 sm:p-6 text-xs sm:text-sm text-gray-700 whitespace-pre-wrap font-mono leading-relaxed">
                  {preview}
                </pre>
              ) : (
                <div className="flex flex-col items-center justify-center h-full min-h-[320px] p-8 text-center">
                  <div className="w-14 h-14 rounded-2xl bg-primary-50 text-primary-400 flex items-center justify-center mb-4">
                    <FileText className="w-7 h-7" aria-hidden="true" />
                  </div>
                  <p className="text-sm font-medium text-gray-500">
                    Your petition preview will appear here
                  </p>
                  <p className="mt-1 text-xs text-gray-400 max-w-xs">
                    Fill in the form and click &ldquo;Generate Petition&rdquo; to see your draft
                  </p>
                </div>
              )}
            </div>

            {hasGenerated && (
              <div className="flex flex-col sm:flex-row gap-2 p-4 border-t border-pink-100 bg-white/80">
                <Button
                  type="button"
                  onClick={handleCopy}
                  variant="secondary"
                  size="sm"
                  className="flex-1 justify-center"
                >
                  {copied ? (
                    <>
                      <Check className="w-4 h-4" aria-hidden="true" />
                      Copied!
                    </>
                  ) : (
                    <>
                      <Copy className="w-4 h-4" aria-hidden="true" />
                      Copy
                    </>
                  )}
                </Button>
                <Button
                  type="button"
                  onClick={handleDownload}
                  size="sm"
                  className="flex-1 justify-center"
                >
                  <Download className="w-4 h-4" aria-hidden="true" />
                  Download
                </Button>
              </div>
            )}
          </Card>

          <p className="mt-4 flex items-start gap-2 text-xs text-gray-400">
            <AlertCircle className="w-4 h-4 shrink-0 mt-0.5" aria-hidden="true" />
            <span>
              This is a client-side draft only — not connected to a backend. Review with a
              registered advocate before filing in court.
            </span>
          </p>
        </div>
      </div>
    </div>
  )
}
